import Head from 'next/head'
import Email from '../components/Email'
import Header from '../components/Header'
import Social from '../components/Social'
import Start from '../components/Start'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-bg ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;800&display=swap" rel="stylesheet" />
      </Head>

      <Header />
      <main className="px-[150px] mx-auto my-0 max-w-[1600px] w-screen">
        <Start />
      </main>
      <Social />
      <Email />

      <footer>

      </footer>
    </div>
  )
}
