import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Email from '../components/Email'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Portfolio from '../components/Portfolio'
import Social from '../components/Social'
import Start from '../components/Start'
import Work from '../components/Work'
import Sidebar from '../components/Sidebar'
import useWidth from '../hooks/useWidth'

export default function Home() {
  const getWidth = useWidth()

  return (
    <div className="bg-bg">
      <Head>
        <title>Cosmic Pixel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;800&display=swap" rel="stylesheet" />
      </Head>

      {
        getWidth <= 768
          ? <Sidebar />
          : <Header />
      }



      <main className="px-[25px] md:px-[100px] xl:px-[150px] mx-auto my-0 max-w-[1600px]">
        <Start />
        <About />
        <Work />
        <Portfolio />
        <Contact />
      </main>

      <Social />
      <Email />
      <Footer />

    </div>
  )
}
